### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by smh1988-2** [learn-co-curriculum/phase-0-working-with-programs-in-bash#1]
### Canvas Link

https://learning.flatironschool.com/courses/4837/pages/working-with-programs-in-bash?module_item_id=305111

### Concern

There is a disconnect between the names used in the examples when running PATH. The names switch between kellyegreene and ianhollander in the text and the examples. It caught me up when first reading it. But I presume it a typo/copy error and I'm not misunderstanding the point?

$ echo $PATH
/Users/**_kellyegreene_**/.rvm/gems/ruby-2.7.4/bin:/Users/kellyegreene/.rvm/gems/ruby-2.7.4@global/bin:/Users/kellyegreene/.rvm/rubies/ruby-2.7.4/bin:/Users/kellyegreene/.nvm/versions/node/v8.9.4/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin:/usr/local/share/npm/lib/node_modules/grunt-cli/bin:/usr/local:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kellyegreene/Library/Android/sdk/tools:/Users/kellyegreene/Library/Android/sdk/platform-tools:/Users/kellyegreene/Library/Android/sdk/tools:/Users/kellyegreene/Library/Android/sdk/platform-tools:/Users/kellyegreene/.rvm/bin
Any program in these directories can be run by simply typing the program name. When kellyegreene types ruby the shell starts by looking at the first directory in the PATH to see if it finds a program that matches.

In this case it would find the ruby program in /Users/**_ianhollander_**/.rvm/rubies/ruby-2.7.4/bin and run it. The first match in the PATH variable wins so the order of the PATH is important.

### Suggested Changes

Makes the names consistent. 

$ echo $PATH
/Users/kellyegreene/.rvm/gems/ruby-2.7.4/bin:/Users/kellyegreene/.rvm/gems/ruby-2.7.4@global/bin:/Users/kellyegreene/.rvm/rubies/ruby-2.7.4/bin:/Users/kellyegreene/.nvm/versions/node/v8.9.4/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin:/usr/local/share/npm/lib/node_modules/grunt-cli/bin:/usr/local:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kellyegreene/Library/Android/sdk/tools:/Users/kellyegreene/Library/Android/sdk/platform-tools:/Users/kellyegreene/Library/Android/sdk/tools:/Users/kellyegreene/Library/Android/sdk/platform-tools:/Users/kellyegreene/.rvm/bin
Any program in these directories can be run by simply typing the program name. When kellyegreene types ruby the shell starts by looking at the first directory in the PATH to see if it finds a program that matches.

In this case it would find the ruby program in /Users/kellyegreene/.rvm/rubies/ruby-2.7.4/bin and run it. The first match in the PATH variable wins so the order of the PATH is important.

If this directory were not in the PATH, kellyegreene would have to do one of the following to run ruby -v — a command that shows the program's version.

$ cd /Users/kellyegreene/.rvm/rubies/ruby-2.7.4/bin
$ ./ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]
or

$ /Users/kellyegreene/.rvm/rubies/ruby-2.7.4/bin/ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]

**Comment by graciemcguire** [comment]
Hey @smh1988-2 ! Thanks for raising this issue. We have changed the inconsistencies in this lab, you can see the changes [here](https://github.com/learn-co-curriculum/phase-0-working-with-programs-in-bash/commit/38a4b9448473721c79608ebe1449ed80a75c5192) if you would like.  
Please note these changes will not be reflected in your cohort's Canvas, but are in GitHub, as well as in Canvas for future cohorts. 
Thanks again!
